import {
  Announcement,
  AttendanceRecord,
  AuditLog,
  Combination,
  Department,
  DisciplineCase,
  Examination,
  ExamMark,
  FeePayment,
  School,
  SchoolMembership,
  Stream,
  Student,
  Subject,
} from '../types';

export const DEMO_SCHOOL: School = {
  id: 'school-mwanza-modern-001',
  name: 'Mwanza Modern Secondary School',
  code: 'TZS-MWZ-891',
  registrationNumber: 'S.4892/2014',
  ownershipType: 'Private',
  educationLevels: ['O-Level', 'A-Level'],
  region: 'Mwanza',
  district: 'Nyamagana',
  ward: 'Mirongo',
  address: 'Plot 42, Capripoint Hills, Mwanza, Tanzania',
  phone: '+255 784 123 456',
  email: 'info@mwanzamodern.ac.tz',
  website: 'https://mwanzamodern.ac.tz',
  motto: 'Elimu ni Mwanga na Nguvu (Education is Light & Power)',
  logoUrl: 'https://images.unsplash.com/photo-1546410531-bb4caa6b424d?w=150&auto=format&fit=crop&q=80',
  ownerId: 'user-owner-001',
  ownerName: 'Dr. Aloyce M. Mtei',
  academicYear: '2026',
  currentTerm: 'Term 1',
  status: 'active',
  createdAt: '2024-01-10T08:00:00Z',
};

export const DEMO_DEPARTMENTS: Department[] = [
  {
    id: 'dept-sci',
    schoolId: 'school-mwanza-modern-001',
    name: 'Science & Laboratory Department',
    code: 'SCI',
    description: 'Physics, Chemistry, and Biology sciences with practical laboratory research.',
    hodId: 'user-john-magesa',
    hodName: 'Mr. John Magesa',
    memberIds: ['user-john-magesa', 'user-grace-mushi'],
    status: 'active',
    createdAt: '2024-01-12T00:00:00Z',
  },
  {
    id: 'dept-ict',
    schoolId: 'school-mwanza-modern-001',
    name: 'ICT & Computer Studies',
    code: 'ICT',
    description: 'Digital literacy, programming fundamentals, information systems, and computer hardware.',
    hodId: 'user-sarah-mtui',
    hodName: 'Madam Sarah Mtui',
    memberIds: ['user-sarah-mtui'],
    status: 'active',
    createdAt: '2024-01-12T00:00:00Z',
  },
  {
    id: 'dept-math',
    schoolId: 'school-mwanza-modern-001',
    name: 'Mathematics Department',
    code: 'MATH',
    description: 'Basic Mathematics, Additional Mathematics, and Advanced Pure Mathematics.',
    hodId: 'user-mary-chacha',
    hodName: 'Madam Mary Chacha',
    memberIds: ['user-mary-chacha', 'user-john-magesa'],
    status: 'active',
    createdAt: '2024-01-12T00:00:00Z',
  },
  {
    id: 'dept-arts',
    schoolId: 'school-mwanza-modern-001',
    name: 'Humanities & Social Sciences',
    code: 'ARTS',
    description: 'History, Geography, Civics, and General Studies.',
    hodId: 'user-peter-mwita',
    hodName: 'Mwl. Peter Mwita',
    memberIds: ['user-peter-mwita'],
    status: 'active',
    createdAt: '2024-01-12T00:00:00Z',
  },
  {
    id: 'dept-lang',
    schoolId: 'school-mwanza-modern-001',
    name: 'Languages & Literature',
    code: 'LANG',
    description: 'Kiswahili Sanifu, English Language and Literature in English.',
    hodId: 'user-joseph-makala',
    hodName: 'Mwl. Joseph Makala',
    memberIds: ['user-joseph-makala', 'user-peter-mwita'],
    status: 'active',
    createdAt: '2024-01-12T00:00:00Z',
  },
];

export const DEMO_COMBINATIONS: Combination[] = [
  {
    id: 'comb-pcm',
    schoolId: 'school-mwanza-modern-001',
    code: 'PCM',
    name: 'Physics, Chemistry, Advanced Mathematics',
    subjectIds: ['sub-phy', 'sub-chem', 'sub-bam'],
    status: 'active',
    description: 'Premier engineering and technology stream combination.',
  },
  {
    id: 'comb-pcb',
    schoolId: 'school-mwanza-modern-001',
    code: 'PCB',
    name: 'Physics, Chemistry, Biology',
    subjectIds: ['sub-phy', 'sub-chem', 'sub-bio'],
    status: 'active',
    description: 'Medical and life sciences pathway.',
  },
  {
    id: 'comb-hgl',
    schoolId: 'school-mwanza-modern-001',
    code: 'HGL',
    name: 'History, Geography, English Language',
    subjectIds: ['sub-hist', 'sub-geo', 'sub-eng'],
    status: 'active',
    description: 'Humanities, law, diplomacy and social administration.',
  },
  {
    id: 'comb-cbg',
    schoolId: 'school-mwanza-modern-001',
    code: 'CBG',
    name: 'Chemistry, Biology, Geography',
    subjectIds: ['sub-chem', 'sub-bio', 'sub-geo'],
    status: 'active',
    description: 'Environmental, agriculture, and biological sciences pathway.',
  },
];

export const DEMO_STREAMS: Stream[] = [
  {
    id: 'stream-f1a',
    schoolId: 'school-mwanza-modern-001',
    name: 'Form I A',
    code: 'F1-A',
    level: 'O-Level',
    formStandard: 'Form I',
    academicYear: '2026',
    classTeacherId: 'user-john-magesa',
    classTeacherName: 'Mr. John Magesa',
    maxCapacity: 45,
    status: 'active',
  },
  {
    id: 'stream-f1b',
    schoolId: 'school-mwanza-modern-001',
    name: 'Form I B',
    code: 'F1-B',
    level: 'O-Level',
    formStandard: 'Form I',
    academicYear: '2026',
    classTeacherId: 'user-sarah-mtui',
    classTeacherName: 'Madam Sarah Mtui',
    maxCapacity: 45,
    status: 'active',
  },
  {
    id: 'stream-f2a',
    schoolId: 'school-mwanza-modern-001',
    name: 'Form II A',
    code: 'F2-A',
    level: 'O-Level',
    formStandard: 'Form II',
    academicYear: '2026',
    classTeacherId: 'user-grace-mushi',
    classTeacherName: 'Madam Grace Mushi',
    maxCapacity: 45,
    status: 'active',
  },
  {
    id: 'stream-f4-alpha',
    schoolId: 'school-mwanza-modern-001',
    name: 'Form IV Alpha',
    code: 'F4-ALPHA',
    level: 'O-Level',
    formStandard: 'Form IV',
    academicYear: '2026',
    classTeacherId: 'user-mary-chacha',
    classTeacherName: 'Madam Mary Chacha',
    maxCapacity: 40,
    status: 'active',
  },
  {
    id: 'stream-f5-pcm',
    schoolId: 'school-mwanza-modern-001',
    name: 'Form V Science (PCM)',
    code: 'F5-PCM',
    level: 'A-Level',
    formStandard: 'Form V',
    academicYear: '2026',
    classTeacherId: 'user-john-magesa',
    classTeacherName: 'Mr. John Magesa',
    maxCapacity: 35,
    status: 'active',
  },
  {
    id: 'stream-f5-pcb',
    schoolId: 'school-mwanza-modern-001',
    name: 'Form V Life Sciences (PCB)',
    code: 'F5-PCB',
    level: 'A-Level',
    formStandard: 'Form V',
    academicYear: '2026',
    classTeacherId: 'user-grace-mushi',
    classTeacherName: 'Madam Grace Mushi',
    maxCapacity: 35,
    status: 'active',
  },
];

export const DEMO_SUBJECTS: Subject[] = [
  { id: 'sub-math', schoolId: 'school-mwanza-modern-001', name: 'Basic Mathematics', code: 'B.MATH', level: 'O-Level', departmentId: 'dept-math', periodsPerWeek: 6, status: 'active' },
  { id: 'sub-phy', schoolId: 'school-mwanza-modern-001', name: 'Physics', code: 'PHY', level: 'All', departmentId: 'dept-sci', periodsPerWeek: 5, status: 'active' },
  { id: 'sub-chem', schoolId: 'school-mwanza-modern-001', name: 'Chemistry', code: 'CHEM', level: 'All', departmentId: 'dept-sci', periodsPerWeek: 5, status: 'active' },
  { id: 'sub-bio', schoolId: 'school-mwanza-modern-001', name: 'Biology', code: 'BIO', level: 'All', departmentId: 'dept-sci', periodsPerWeek: 5, status: 'active' },
  { id: 'sub-kisw', schoolId: 'school-mwanza-modern-001', name: 'Kiswahili', code: 'KISW', level: 'O-Level', departmentId: 'dept-lang', periodsPerWeek: 4, status: 'active' },
  { id: 'sub-eng', schoolId: 'school-mwanza-modern-001', name: 'English Language', code: 'ENG', level: 'All', departmentId: 'dept-lang', periodsPerWeek: 5, status: 'active' },
  { id: 'sub-geo', schoolId: 'school-mwanza-modern-001', name: 'Geography', code: 'GEO', level: 'All', departmentId: 'dept-arts', periodsPerWeek: 4, status: 'active' },
  { id: 'sub-hist', schoolId: 'school-mwanza-modern-001', name: 'History', code: 'HIST', level: 'All', departmentId: 'dept-arts', periodsPerWeek: 4, status: 'active' },
  { id: 'sub-ict', schoolId: 'school-mwanza-modern-001', name: 'Information & Computer Studies', code: 'ICS', level: 'All', departmentId: 'dept-ict', periodsPerWeek: 4, status: 'active' },
  { id: 'sub-bam', schoolId: 'school-mwanza-modern-001', name: 'Advanced Mathematics', code: 'ADV.MATH', level: 'A-Level', departmentId: 'dept-math', periodsPerWeek: 7, status: 'active' },
];

export const DEMO_MEMBERSHIPS: SchoolMembership[] = [
  {
    id: 'mem-owner',
    schoolId: 'school-mwanza-modern-001',
    schoolName: 'Mwanza Modern Secondary School',
    userId: 'user-owner-001',
    userEmail: 'owner@mwanzamodern.ac.tz',
    userName: 'Dr. Aloyce M. Mtei',
    positions: ['School Owner'],
    permissions: ['school.configure', 'students.view', 'students.create', 'teachers.manage', 'finance.view', 'reports.view', 'audit.view'],
    status: 'active',
    joinedAt: '2024-01-10T08:00:00Z',
  },
  {
    id: 'mem-headmaster',
    schoolId: 'school-mwanza-modern-001',
    schoolName: 'Mwanza Modern Secondary School',
    userId: 'user-peter-mwita',
    userEmail: 'headmaster@mwanzamodern.ac.tz',
    userName: 'Mwl. Peter Mwita',
    positions: ['Headmaster', 'Teacher'],
    permissions: ['students.view', 'teachers.view', 'results.view', 'reports.view', 'discipline.view', 'qa.view'],
    status: 'active',
    joinedAt: '2024-01-11T09:00:00Z',
  },
  {
    id: 'mem-academic',
    schoolId: 'school-mwanza-modern-001',
    schoolName: 'Mwanza Modern Secondary School',
    userId: 'user-mary-chacha',
    userEmail: 'academic@mwanzamodern.ac.tz',
    userName: 'Madam Mary Chacha',
    positions: ['Academic Mistress', 'Head of Department', 'Class Teacher', 'Teacher'],
    permissions: ['marks.enter', 'marks.submit', 'marks.verify', 'marks.approve', 'results.release', 'results.lock', 'reports.view', 'students.view'],
    status: 'active',
    joinedAt: '2024-01-12T09:00:00Z',
    departmentId: 'dept-math',
    assignedStreamIds: ['stream-f4-alpha'],
    assignedSubjectIds: ['sub-math'],
  },
  {
    id: 'mem-john',
    schoolId: 'school-mwanza-modern-001',
    schoolName: 'Mwanza Modern Secondary School',
    userId: 'user-john-magesa',
    userEmail: 'j.magesa@mwanzamodern.ac.tz',
    userName: 'Mr. John Magesa',
    positions: ['Head of Department', 'Class Teacher', 'Teacher'],
    permissions: ['marks.enter', 'marks.submit', 'attendance.mark', 'attendance.view', 'students.view', 'results.view'],
    status: 'active',
    joinedAt: '2024-01-15T08:00:00Z',
    departmentId: 'dept-sci',
    assignedStreamIds: ['stream-f1a', 'stream-f5-pcm'],
    assignedSubjectIds: ['sub-phy'],
  },
  {
    id: 'mem-accountant',
    schoolId: 'school-mwanza-modern-001',
    schoolName: 'Mwanza Modern Secondary School',
    userId: 'user-baraka-kibona',
    userEmail: 'accounts@mwanzamodern.ac.tz',
    userName: 'Mr. Baraka Kibona (CPA)',
    positions: ['Accountant'],
    permissions: ['finance.view', 'finance.manage', 'reports.view', 'students.view'],
    status: 'active',
    joinedAt: '2024-01-16T08:00:00Z',
  },
  {
    id: 'mem-discipline',
    schoolId: 'school-mwanza-modern-001',
    schoolName: 'Mwanza Modern Secondary School',
    userId: 'user-grace-mushi',
    userEmail: 'g.mushi@mwanzamodern.ac.tz',
    userName: 'Madam Grace Mushi',
    positions: ['Discipline Mistress', 'Class Teacher', 'Teacher'],
    permissions: ['discipline.view', 'discipline.manage', 'attendance.mark', 'marks.enter', 'students.view'],
    status: 'active',
    joinedAt: '2024-01-18T08:00:00Z',
    departmentId: 'dept-sci',
    assignedStreamIds: ['stream-f2a', 'stream-f5-pcb'],
    assignedSubjectIds: ['sub-bio'],
  },
  {
    id: 'mem-qa',
    schoolId: 'school-mwanza-modern-001',
    schoolName: 'Mwanza Modern Secondary School',
    userId: 'user-joseph-makala',
    userEmail: 'qa@mwanzamodern.ac.tz',
    userName: 'Mwl. Joseph Makala',
    positions: ['Quality Assurance', 'Head of Department', 'Teacher'],
    permissions: ['qa.view', 'qa.manage', 'reports.view', 'students.view', 'results.view'],
    status: 'active',
    joinedAt: '2024-01-20T08:00:00Z',
    departmentId: 'dept-lang',
    assignedSubjectIds: ['sub-eng'],
  },
  {
    id: 'mem-parent',
    schoolId: 'school-mwanza-modern-001',
    schoolName: 'Mwanza Modern Secondary School',
    userId: 'user-parent-bakari',
    userEmail: 'bakari.parent@gmail.com',
    userName: 'Eng. Bakari H. Mwinyi',
    positions: ['Parent'],
    permissions: ['results.view', 'attendance.view', 'finance.view'],
    status: 'active',
    joinedAt: '2024-02-01T08:00:00Z',
  },
  {
    id: 'mem-student',
    schoolId: 'school-mwanza-modern-001',
    schoolName: 'Mwanza Modern Secondary School',
    userId: 'user-student-juma',
    userEmail: 'juma.bakari@students.mwanzamodern.ac.tz',
    userName: 'Juma Bakari Mwinyi',
    positions: ['Student'],
    permissions: ['results.view', 'attendance.view'],
    status: 'active',
    joinedAt: '2024-02-01T08:00:00Z',
  },
];

export const DEMO_STUDENTS: Student[] = [
  {
    id: 'stu-001',
    schoolId: 'school-mwanza-modern-001',
    studentId: 'STU-2026-001',
    admissionNumber: 'MWS/2023/089',
    fullName: 'Juma Bakari Mwinyi',
    gender: 'Male',
    dateOfBirth: '2008-04-14',
    level: 'O-Level',
    formStandard: 'Form IV',
    streamId: 'stream-f4-alpha',
    streamName: 'Form IV Alpha',
    parentName: 'Eng. Bakari H. Mwinyi',
    parentPhone: '+255 754 990 112',
    parentEmail: 'bakari.parent@gmail.com',
    address: 'Nyamagana, Mwanza',
    previousSchool: 'Isamilo Primary School',
    status: 'Active',
    admissionDate: '2023-01-09',
    academicYear: '2026',
    movementHistory: [
      {
        id: 'mov-1',
        type: 'Class Promotion',
        fromValue: 'Form III',
        toValue: 'Form IV',
        reason: 'Passed Form III Annual Examinations',
        approvedBy: 'Madam Mary Chacha',
        timestamp: '2025-12-15T10:00:00Z',
      },
    ],
  },
  {
    id: 'stu-002',
    schoolId: 'school-mwanza-modern-001',
    studentId: 'STU-2026-002',
    admissionNumber: 'MWS/2023/094',
    fullName: 'Rehema Salum Kitwana',
    gender: 'Female',
    dateOfBirth: '2008-09-22',
    level: 'O-Level',
    formStandard: 'Form IV',
    streamId: 'stream-f4-alpha',
    streamName: 'Form IV Alpha',
    parentName: 'Mama Salum Kitwana',
    parentPhone: '+255 767 881 234',
    parentEmail: 'salum.kitwana@gmail.com',
    address: 'Capripoint, Mwanza',
    previousSchool: 'Lake English Medium Primary',
    status: 'Active',
    admissionDate: '2023-01-09',
    academicYear: '2026',
  },
  {
    id: 'stu-003',
    schoolId: 'school-mwanza-modern-001',
    studentId: 'STU-2026-003',
    admissionNumber: 'MWS/2023/110',
    fullName: 'Neema Emmanuel Ndalichako',
    gender: 'Female',
    dateOfBirth: '2008-11-05',
    level: 'O-Level',
    formStandard: 'Form IV',
    streamId: 'stream-f4-alpha',
    streamName: 'Form IV Alpha',
    parentName: 'Rev. Emmanuel Ndalichako',
    parentPhone: '+255 788 334 119',
    parentEmail: 'ndalichako@yahoo.com',
    address: 'Buzuruga, Mwanza',
    previousSchool: 'Victoria Primary School',
    status: 'Active',
    admissionDate: '2023-01-09',
    academicYear: '2026',
  },
  {
    id: 'stu-004',
    schoolId: 'school-mwanza-modern-001',
    studentId: 'STU-2026-004',
    admissionNumber: 'MWS/2023/122',
    fullName: 'Kelvin Mushi Lyimo',
    gender: 'Male',
    dateOfBirth: '2008-01-30',
    level: 'O-Level',
    formStandard: 'Form IV',
    streamId: 'stream-f4-alpha',
    streamName: 'Form IV Alpha',
    parentName: 'Dr. Frank Lyimo',
    parentPhone: '+255 713 445 667',
    parentEmail: 'flyimo@gmail.com',
    address: 'Igoma, Mwanza',
    previousSchool: 'Highland Primary School',
    status: 'Active',
    admissionDate: '2023-01-09',
    academicYear: '2026',
  },
  {
    id: 'stu-005',
    schoolId: 'school-mwanza-modern-001',
    studentId: 'STU-2026-005',
    admissionNumber: 'MWS/2023/145',
    fullName: 'Aisha Nassoro Mpemba',
    gender: 'Female',
    dateOfBirth: '2008-07-19',
    level: 'O-Level',
    formStandard: 'Form IV',
    streamId: 'stream-f4-alpha',
    streamName: 'Form IV Alpha',
    parentName: 'Nassoro Mpemba',
    parentPhone: '+255 755 120 987',
    address: 'Pasiansi, Mwanza',
    status: 'Active',
    admissionDate: '2023-01-09',
    academicYear: '2026',
  },
  {
    id: 'stu-006',
    schoolId: 'school-mwanza-modern-001',
    studentId: 'STU-2026-006',
    admissionNumber: 'MWS/2025/012',
    fullName: 'Baraka Josephat Malecela',
    gender: 'Male',
    dateOfBirth: '2007-03-11',
    level: 'A-Level',
    formStandard: 'Form V',
    streamId: 'stream-f5-pcm',
    streamName: 'Form V Science (PCM)',
    combinationId: 'comb-pcm',
    combinationCode: 'PCM',
    parentName: 'Josephat Malecela',
    parentPhone: '+255 762 300 456',
    address: 'Kirumba, Mwanza',
    status: 'Active',
    admissionDate: '2025-07-02',
    academicYear: '2026',
  },
  {
    id: 'stu-007',
    schoolId: 'school-mwanza-modern-001',
    studentId: 'STU-2026-007',
    admissionNumber: 'MWS/2025/028',
    fullName: 'Esther Lucas Mmbaga',
    gender: 'Female',
    dateOfBirth: '2007-06-18',
    level: 'A-Level',
    formStandard: 'Form V',
    streamId: 'stream-f5-pcb',
    streamName: 'Form V Life Sciences (PCB)',
    combinationId: 'comb-pcb',
    combinationCode: 'PCB',
    parentName: 'Mama Lucas Mmbaga',
    parentPhone: '+255 784 776 543',
    address: 'Kisesa, Mwanza',
    status: 'Active',
    admissionDate: '2025-07-02',
    academicYear: '2026',
  },
  {
    id: 'stu-008',
    schoolId: 'school-mwanza-modern-001',
    studentId: 'STU-2026-008',
    admissionNumber: 'MWS/2026/001',
    fullName: 'Goodluck Charles Mlinga',
    gender: 'Male',
    dateOfBirth: '2011-02-14',
    level: 'O-Level',
    formStandard: 'Form I',
    streamId: 'stream-f1a',
    streamName: 'Form I A',
    parentName: 'Charles Mlinga',
    parentPhone: '+255 754 112 334',
    address: 'Nyegezi, Mwanza',
    status: 'Active',
    admissionDate: '2026-01-12',
    academicYear: '2026',
  },
];

export const DEMO_EXAMINATIONS: Examination[] = [
  {
    id: 'exam-f4-premock-2026',
    schoolId: 'school-mwanza-modern-001',
    name: 'Form IV Pre-NECTA Mock Examination 2026',
    type: 'Mock',
    academicYear: '2026',
    term: 'Term 1',
    level: 'O-Level',
    formStandard: 'Form IV',
    subjectIds: ['sub-math', 'sub-phy', 'sub-chem', 'sub-bio', 'sub-kisw', 'sub-eng', 'sub-geo', 'sub-hist', 'sub-ict'],
    startDate: '2026-02-16',
    endDate: '2026-02-27',
    maxScore: 100,
    status: 'RELEASED',
    releasedAt: '2026-03-02T14:30:00Z',
    releasedBy: 'Madam Mary Chacha (Academic Mistress)',
    approvedBy: 'Mwl. Peter Mwita (Headmaster)',
  },
  {
    id: 'exam-f2-midterm-2026',
    schoolId: 'school-mwanza-modern-001',
    name: 'Form II Mid-Term Examination 2026',
    type: 'Mid-Term',
    academicYear: '2026',
    term: 'Term 1',
    level: 'O-Level',
    formStandard: 'Form II',
    subjectIds: ['sub-math', 'sub-phy', 'sub-chem', 'sub-bio', 'sub-kisw', 'sub-eng', 'sub-geo'],
    startDate: '2026-03-09',
    endDate: '2026-03-13',
    maxScore: 100,
    status: 'APPROVED',
    approvedBy: 'Madam Mary Chacha',
  },
];

export const DEMO_MARKS: ExamMark[] = [
  // Juma Bakari (STU-001) - High Performer (Div I)
  { id: 'mk-101', schoolId: 'school-mwanza-modern-001', examId: 'exam-f4-premock-2026', studentId: 'stu-001', subjectId: 'sub-math', score: 88, maxScore: 100, isAbsent: false, isExcused: false, teacherId: 'user-mary-chacha', status: 'RELEASED' },
  { id: 'mk-102', schoolId: 'school-mwanza-modern-001', examId: 'exam-f4-premock-2026', studentId: 'stu-001', subjectId: 'sub-phy', score: 82, maxScore: 100, isAbsent: false, isExcused: false, teacherId: 'user-john-magesa', status: 'RELEASED' },
  { id: 'mk-103', schoolId: 'school-mwanza-modern-001', examId: 'exam-f4-premock-2026', studentId: 'stu-001', subjectId: 'sub-chem', score: 79, maxScore: 100, isAbsent: false, isExcused: false, teacherId: 'user-john-magesa', status: 'RELEASED' },
  { id: 'mk-104', schoolId: 'school-mwanza-modern-001', examId: 'exam-f4-premock-2026', studentId: 'stu-001', subjectId: 'sub-bio', score: 85, maxScore: 100, isAbsent: false, isExcused: false, teacherId: 'user-grace-mushi', status: 'RELEASED' },
  { id: 'mk-105', schoolId: 'school-mwanza-modern-001', examId: 'exam-f4-premock-2026', studentId: 'stu-001', subjectId: 'sub-kisw', score: 76, maxScore: 100, isAbsent: false, isExcused: false, teacherId: 'user-peter-mwita', status: 'RELEASED' },
  { id: 'mk-106', schoolId: 'school-mwanza-modern-001', examId: 'exam-f4-premock-2026', studentId: 'stu-001', subjectId: 'sub-eng', score: 84, maxScore: 100, isAbsent: false, isExcused: false, teacherId: 'user-joseph-makala', status: 'RELEASED' },
  { id: 'mk-107', schoolId: 'school-mwanza-modern-001', examId: 'exam-f4-premock-2026', studentId: 'stu-001', subjectId: 'sub-geo', score: 80, maxScore: 100, isAbsent: false, isExcused: false, teacherId: 'user-peter-mwita', status: 'RELEASED' },
  { id: 'mk-108', schoolId: 'school-mwanza-modern-001', examId: 'exam-f4-premock-2026', studentId: 'stu-001', subjectId: 'sub-hist', score: 78, maxScore: 100, isAbsent: false, isExcused: false, teacherId: 'user-peter-mwita', status: 'RELEASED' },
  { id: 'mk-109', schoolId: 'school-mwanza-modern-001', examId: 'exam-f4-premock-2026', studentId: 'stu-001', subjectId: 'sub-ict', score: 92, maxScore: 100, isAbsent: false, isExcused: false, teacherId: 'user-sarah-mtui', status: 'RELEASED' },

  // Rehema Salum (STU-002) - Excellent Performer (Div I)
  { id: 'mk-201', schoolId: 'school-mwanza-modern-001', examId: 'exam-f4-premock-2026', studentId: 'stu-002', subjectId: 'sub-math', score: 91, maxScore: 100, isAbsent: false, isExcused: false, teacherId: 'user-mary-chacha', status: 'RELEASED' },
  { id: 'mk-202', schoolId: 'school-mwanza-modern-001', examId: 'exam-f4-premock-2026', studentId: 'stu-002', subjectId: 'sub-phy', score: 87, maxScore: 100, isAbsent: false, isExcused: false, teacherId: 'user-john-magesa', status: 'RELEASED' },
  { id: 'mk-203', schoolId: 'school-mwanza-modern-001', examId: 'exam-f4-premock-2026', studentId: 'stu-002', subjectId: 'sub-chem', score: 84, maxScore: 100, isAbsent: false, isExcused: false, teacherId: 'user-john-magesa', status: 'RELEASED' },
  { id: 'mk-204', schoolId: 'school-mwanza-modern-001', examId: 'exam-f4-premock-2026', studentId: 'stu-002', subjectId: 'sub-bio', score: 89, maxScore: 100, isAbsent: false, isExcused: false, teacherId: 'user-grace-mushi', status: 'RELEASED' },
  { id: 'mk-205', schoolId: 'school-mwanza-modern-001', examId: 'exam-f4-premock-2026', studentId: 'stu-002', subjectId: 'sub-kisw', score: 82, maxScore: 100, isAbsent: false, isExcused: false, teacherId: 'user-peter-mwita', status: 'RELEASED' },
  { id: 'mk-206', schoolId: 'school-mwanza-modern-001', examId: 'exam-f4-premock-2026', studentId: 'stu-002', subjectId: 'sub-eng', score: 90, maxScore: 100, isAbsent: false, isExcused: false, teacherId: 'user-joseph-makala', status: 'RELEASED' },
  { id: 'mk-207', schoolId: 'school-mwanza-modern-001', examId: 'exam-f4-premock-2026', studentId: 'stu-002', subjectId: 'sub-geo', score: 85, maxScore: 100, isAbsent: false, isExcused: false, teacherId: 'user-peter-mwita', status: 'RELEASED' },
  { id: 'mk-208', schoolId: 'school-mwanza-modern-001', examId: 'exam-f4-premock-2026', studentId: 'stu-002', subjectId: 'sub-hist', score: 86, maxScore: 100, isAbsent: false, isExcused: false, teacherId: 'user-peter-mwita', status: 'RELEASED' },
  { id: 'mk-209', schoolId: 'school-mwanza-modern-001', examId: 'exam-f4-premock-2026', studentId: 'stu-002', subjectId: 'sub-ict', score: 95, maxScore: 100, isAbsent: false, isExcused: false, teacherId: 'user-sarah-mtui', status: 'RELEASED' },

  // Neema Emmanuel (STU-003) - Division II
  { id: 'mk-301', schoolId: 'school-mwanza-modern-001', examId: 'exam-f4-premock-2026', studentId: 'stu-003', subjectId: 'sub-math', score: 68, maxScore: 100, isAbsent: false, isExcused: false, teacherId: 'user-mary-chacha', status: 'RELEASED' },
  { id: 'mk-302', schoolId: 'school-mwanza-modern-001', examId: 'exam-f4-premock-2026', studentId: 'stu-003', subjectId: 'sub-phy', score: 62, maxScore: 100, isAbsent: false, isExcused: false, teacherId: 'user-john-magesa', status: 'RELEASED' },
  { id: 'mk-303', schoolId: 'school-mwanza-modern-001', examId: 'exam-f4-premock-2026', studentId: 'stu-003', subjectId: 'sub-chem', score: 65, maxScore: 100, isAbsent: false, isExcused: false, teacherId: 'user-john-magesa', status: 'RELEASED' },
  { id: 'mk-304', schoolId: 'school-mwanza-modern-001', examId: 'exam-f4-premock-2026', studentId: 'stu-003', subjectId: 'sub-bio', score: 72, maxScore: 100, isAbsent: false, isExcused: false, teacherId: 'user-grace-mushi', status: 'RELEASED' },
  { id: 'mk-305', schoolId: 'school-mwanza-modern-001', examId: 'exam-f4-premock-2026', studentId: 'stu-003', subjectId: 'sub-kisw', score: 70, maxScore: 100, isAbsent: false, isExcused: false, teacherId: 'user-peter-mwita', status: 'RELEASED' },
  { id: 'mk-306', schoolId: 'school-mwanza-modern-001', examId: 'exam-f4-premock-2026', studentId: 'stu-003', subjectId: 'sub-eng', score: 74, maxScore: 100, isAbsent: false, isExcused: false, teacherId: 'user-joseph-makala', status: 'RELEASED' },
  { id: 'mk-307', schoolId: 'school-mwanza-modern-001', examId: 'exam-f4-premock-2026', studentId: 'stu-003', subjectId: 'sub-geo', score: 69, maxScore: 100, isAbsent: false, isExcused: false, teacherId: 'user-peter-mwita', status: 'RELEASED' },
  { id: 'mk-308', schoolId: 'school-mwanza-modern-001', examId: 'exam-f4-premock-2026', studentId: 'stu-003', subjectId: 'sub-hist', score: 71, maxScore: 100, isAbsent: false, isExcused: false, teacherId: 'user-peter-mwita', status: 'RELEASED' },
  { id: 'mk-309', schoolId: 'school-mwanza-modern-001', examId: 'exam-f4-premock-2026', studentId: 'stu-003', subjectId: 'sub-ict', score: 80, maxScore: 100, isAbsent: false, isExcused: false, teacherId: 'user-sarah-mtui', status: 'RELEASED' },

  // Kelvin Mushi (STU-004) - Division III
  { id: 'mk-401', schoolId: 'school-mwanza-modern-001', examId: 'exam-f4-premock-2026', studentId: 'stu-004', subjectId: 'sub-math', score: 48, maxScore: 100, isAbsent: false, isExcused: false, teacherId: 'user-mary-chacha', status: 'RELEASED' },
  { id: 'mk-402', schoolId: 'school-mwanza-modern-001', examId: 'exam-f4-premock-2026', studentId: 'stu-004', subjectId: 'sub-phy', score: 52, maxScore: 100, isAbsent: false, isExcused: false, teacherId: 'user-john-magesa', status: 'RELEASED' },
  { id: 'mk-403', schoolId: 'school-mwanza-modern-001', examId: 'exam-f4-premock-2026', studentId: 'stu-004', subjectId: 'sub-chem', score: 50, maxScore: 100, isAbsent: false, isExcused: false, teacherId: 'user-john-magesa', status: 'RELEASED' },
  { id: 'mk-404', schoolId: 'school-mwanza-modern-001', examId: 'exam-f4-premock-2026', studentId: 'stu-004', subjectId: 'sub-bio', score: 58, maxScore: 100, isAbsent: false, isExcused: false, teacherId: 'user-grace-mushi', status: 'RELEASED' },
  { id: 'mk-405', schoolId: 'school-mwanza-modern-001', examId: 'exam-f4-premock-2026', studentId: 'stu-004', subjectId: 'sub-kisw', score: 62, maxScore: 100, isAbsent: false, isExcused: false, teacherId: 'user-peter-mwita', status: 'RELEASED' },
  { id: 'mk-406', schoolId: 'school-mwanza-modern-001', examId: 'exam-f4-premock-2026', studentId: 'stu-004', subjectId: 'sub-eng', score: 56, maxScore: 100, isAbsent: false, isExcused: false, teacherId: 'user-joseph-makala', status: 'RELEASED' },
  { id: 'mk-407', schoolId: 'school-mwanza-modern-001', examId: 'exam-f4-premock-2026', studentId: 'stu-004', subjectId: 'sub-geo', score: 54, maxScore: 100, isAbsent: false, isExcused: false, teacherId: 'user-peter-mwita', status: 'RELEASED' },
  { id: 'mk-408', schoolId: 'school-mwanza-modern-001', examId: 'exam-f4-premock-2026', studentId: 'stu-004', subjectId: 'sub-hist', score: 49, maxScore: 100, isAbsent: false, isExcused: false, teacherId: 'user-peter-mwita', status: 'RELEASED' },
  { id: 'mk-409', schoolId: 'school-mwanza-modern-001', examId: 'exam-f4-premock-2026', studentId: 'stu-004', subjectId: 'sub-ict', score: 64, maxScore: 100, isAbsent: false, isExcused: false, teacherId: 'user-sarah-mtui', status: 'RELEASED' },

  // Aisha Nassoro (STU-005) - Division I
  { id: 'mk-501', schoolId: 'school-mwanza-modern-001', examId: 'exam-f4-premock-2026', studentId: 'stu-005', subjectId: 'sub-math', score: 85, maxScore: 100, isAbsent: false, isExcused: false, teacherId: 'user-mary-chacha', status: 'RELEASED' },
  { id: 'mk-502', schoolId: 'school-mwanza-modern-001', examId: 'exam-f4-premock-2026', studentId: 'stu-005', subjectId: 'sub-phy', score: 80, maxScore: 100, isAbsent: false, isExcused: false, teacherId: 'user-john-magesa', status: 'RELEASED' },
  { id: 'mk-503', schoolId: 'school-mwanza-modern-001', examId: 'exam-f4-premock-2026', studentId: 'stu-005', subjectId: 'sub-chem', score: 78, maxScore: 100, isAbsent: false, isExcused: false, teacherId: 'user-john-magesa', status: 'RELEASED' },
  { id: 'mk-504', schoolId: 'school-mwanza-modern-001', examId: 'exam-f4-premock-2026', studentId: 'stu-005', subjectId: 'sub-bio', score: 86, maxScore: 100, isAbsent: false, isExcused: false, teacherId: 'user-grace-mushi', status: 'RELEASED' },
  { id: 'mk-505', schoolId: 'school-mwanza-modern-001', examId: 'exam-f4-premock-2026', studentId: 'stu-005', subjectId: 'sub-kisw', score: 84, maxScore: 100, isAbsent: false, isExcused: false, teacherId: 'user-peter-mwita', status: 'RELEASED' },
  { id: 'mk-506', schoolId: 'school-mwanza-modern-001', examId: 'exam-f4-premock-2026', studentId: 'stu-005', subjectId: 'sub-eng', score: 88, maxScore: 100, isAbsent: false, isExcused: false, teacherId: 'user-joseph-makala', status: 'RELEASED' },
  { id: 'mk-507', schoolId: 'school-mwanza-modern-001', examId: 'exam-f4-premock-2026', studentId: 'stu-005', subjectId: 'sub-geo', score: 82, maxScore: 100, isAbsent: false, isExcused: false, teacherId: 'user-peter-mwita', status: 'RELEASED' },
  { id: 'mk-508', schoolId: 'school-mwanza-modern-001', examId: 'exam-f4-premock-2026', studentId: 'stu-005', subjectId: 'sub-hist', score: 83, maxScore: 100, isAbsent: false, isExcused: false, teacherId: 'user-peter-mwita', status: 'RELEASED' },
  { id: 'mk-509', schoolId: 'school-mwanza-modern-001', examId: 'exam-f4-premock-2026', studentId: 'stu-005', subjectId: 'sub-ict', score: 90, maxScore: 100, isAbsent: false, isExcused: false, teacherId: 'user-sarah-mtui', status: 'RELEASED' },
];

export const DEMO_ATTENDANCE: AttendanceRecord[] = [
  { id: 'att-1', schoolId: 'school-mwanza-modern-001', studentId: 'stu-001', studentName: 'Juma Bakari Mwinyi', streamId: 'stream-f4-alpha', date: '2026-10-01', status: 'Present', markedBy: 'user-mary-chacha', markedByName: 'Madam Mary Chacha' },
  { id: 'att-2', schoolId: 'school-mwanza-modern-001', studentId: 'stu-002', studentName: 'Rehema Salum Kitwana', streamId: 'stream-f4-alpha', date: '2026-10-01', status: 'Present', markedBy: 'user-mary-chacha', markedByName: 'Madam Mary Chacha' },
  { id: 'att-3', schoolId: 'school-mwanza-modern-001', studentId: 'stu-003', studentName: 'Neema Emmanuel Ndalichako', streamId: 'stream-f4-alpha', date: '2026-10-01', status: 'Present', markedBy: 'user-mary-chacha', markedByName: 'Madam Mary Chacha' },
  { id: 'att-4', schoolId: 'school-mwanza-modern-001', studentId: 'stu-004', studentName: 'Kelvin Mushi Lyimo', streamId: 'stream-f4-alpha', date: '2026-10-01', status: 'Late', remark: 'Arrived at 07:45 due to transit delay', markedBy: 'user-mary-chacha', markedByName: 'Madam Mary Chacha' },
  { id: 'att-5', schoolId: 'school-mwanza-modern-001', studentId: 'stu-005', studentName: 'Aisha Nassoro Mpemba', streamId: 'stream-f4-alpha', date: '2026-10-01', status: 'Present', markedBy: 'user-mary-chacha', markedByName: 'Madam Mary Chacha' },
  { id: 'att-6', schoolId: 'school-mwanza-modern-001', studentId: 'stu-006', studentName: 'Baraka Josephat Malecela', streamId: 'stream-f5-pcm', date: '2026-10-01', status: 'Present', markedBy: 'user-john-magesa', markedByName: 'Mr. John Magesa' },
  { id: 'att-7', schoolId: 'school-mwanza-modern-001', studentId: 'stu-007', studentName: 'Esther Lucas Mmbaga', streamId: 'stream-f5-pcb', date: '2026-10-01', status: 'Present', markedBy: 'user-grace-mushi', markedByName: 'Madam Grace Mushi' },
  { id: 'att-8', schoolId: 'school-mwanza-modern-001', studentId: 'stu-008', studentName: 'Goodluck Charles Mlinga', streamId: 'stream-f1a', date: '2026-10-01', status: 'Excused', remark: 'Attending clinic appointment with parent note', markedBy: 'user-john-magesa', markedByName: 'Mr. John Magesa' },
];

export const DEMO_FEES: FeePayment[] = [
  {
    id: 'fee-1',
    schoolId: 'school-mwanza-modern-001',
    studentId: 'stu-001',
    studentName: 'Juma Bakari Mwinyi',
    admissionNumber: 'MWS/2023/089',
    amount: 1500000,
    paymentMethod: 'Bank',
    referenceNumber: 'NMB-TXN-9844210',
    term: 'Term 1',
    academicYear: '2026',
    feeType: 'Tuition Fee',
    date: '2026-01-14',
    recordedBy: 'user-baraka-kibona',
    recordedByName: 'Mr. Baraka Kibona',
    receiptNumber: 'RCPT-2026-0041',
    status: 'Completed',
  },
  {
    id: 'fee-2',
    schoolId: 'school-mwanza-modern-001',
    studentId: 'stu-002',
    studentName: 'Rehema Salum Kitwana',
    admissionNumber: 'MWS/2023/094',
    amount: 1500000,
    paymentMethod: 'M-Pesa',
    referenceNumber: 'MP-QB90812901',
    term: 'Term 1',
    academicYear: '2026',
    feeType: 'Tuition Fee',
    date: '2026-01-15',
    recordedBy: 'user-baraka-kibona',
    recordedByName: 'Mr. Baraka Kibona',
    receiptNumber: 'RCPT-2026-0048',
    status: 'Completed',
  },
  {
    id: 'fee-3',
    schoolId: 'school-mwanza-modern-001',
    studentId: 'stu-003',
    studentName: 'Neema Emmanuel Ndalichako',
    admissionNumber: 'MWS/2023/110',
    amount: 1200000,
    paymentMethod: 'Bank',
    referenceNumber: 'CRDB-BK-0019283',
    term: 'Term 1',
    academicYear: '2026',
    feeType: 'Tuition Fee',
    date: '2026-01-16',
    recordedBy: 'user-baraka-kibona',
    recordedByName: 'Mr. Baraka Kibona',
    receiptNumber: 'RCPT-2026-0055',
    status: 'Completed',
  },
  {
    id: 'fee-4',
    schoolId: 'school-mwanza-modern-001',
    studentId: 'stu-006',
    studentName: 'Baraka Josephat Malecela',
    admissionNumber: 'MWS/2025/012',
    amount: 1800000,
    paymentMethod: 'Bank',
    referenceNumber: 'NBC-TF-881299',
    term: 'Term 1',
    academicYear: '2026',
    feeType: 'Boarding Fee',
    date: '2026-01-18',
    recordedBy: 'user-baraka-kibona',
    recordedByName: 'Mr. Baraka Kibona',
    receiptNumber: 'RCPT-2026-0062',
    status: 'Completed',
  },
];

export const DEMO_DISCIPLINE: DisciplineCase[] = [
  {
    id: 'disc-1',
    schoolId: 'school-mwanza-modern-001',
    studentId: 'stu-004',
    studentName: 'Kelvin Mushi Lyimo',
    admissionNumber: 'MWS/2023/122',
    streamName: 'Form IV Alpha',
    title: 'Repeated Morning Lateness',
    description: 'Student arrived past 07:30 AM on three consecutive morning roll calls without valid written excuse.',
    severity: 'Minor',
    actionTaken: 'Verbal Warning & Class Teacher counseling session with record noted',
    reportedBy: 'user-grace-mushi',
    reportedByName: 'Madam Grace Mushi',
    parentNotified: true,
    date: '2026-02-10',
    status: 'Resolved',
  },
  {
    id: 'disc-2',
    schoolId: 'school-mwanza-modern-001',
    studentId: 'stu-008',
    studentName: 'Goodluck Charles Mlinga',
    admissionNumber: 'MWS/2026/001',
    streamName: 'Form I A',
    title: 'Misplaced Science Lab Textbook',
    description: 'Failure to return physics laboratory reference book after library study session.',
    severity: 'Minor',
    actionTaken: 'Assisted librarian with book sorting & replaced volume',
    reportedBy: 'user-john-magesa',
    reportedByName: 'Mr. John Magesa',
    parentNotified: false,
    date: '2026-02-22',
    status: 'Closed',
  },
];

export const DEMO_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'anc-1',
    schoolId: 'school-mwanza-modern-001',
    title: 'Release of Form IV Pre-Mock Examination Results',
    content: 'Matokeo ya Mtihani wa Majaribio (Pre-NECTA Mock) kwa Kidato cha Nne yametolewa rasmi na Ofisi ya Taaluma. Wazazi na wanafunzi wanaweza kutazama matokeo kupitia tovuti hii.',
    authorId: 'user-mary-chacha',
    authorName: 'Madam Mary Chacha (Academic Mistress)',
    targetAudience: 'All',
    createdAt: '2026-03-02T15:00:00Z',
    priority: 'Urgent',
  },
  {
    id: 'anc-2',
    schoolId: 'school-mwanza-modern-001',
    title: 'Form II Parents & Academic Consultation Day',
    content: 'Mkutano wa Kitaaluma wa Wazazi wa Wanafunzi wa Kidato cha Pili utafanyika Jumamosi saa 3:00 asubuhi katika Ukumbi Mkuu wa Shule.',
    authorId: 'user-peter-mwita',
    authorName: 'Mwl. Peter Mwita (Headmaster)',
    targetAudience: 'Parents',
    createdAt: '2026-03-05T09:00:00Z',
    priority: 'Important',
  },
  {
    id: 'anc-3',
    schoolId: 'school-mwanza-modern-001',
    title: 'Inter-School Science & ICT Innovation Fair',
    content: 'All Form V and VI science students are invited to submit project prototypes for the Lake Zone High Schools Science Exhibition by end of month.',
    authorId: 'user-john-magesa',
    authorName: 'Mr. John Magesa (HOD Science)',
    targetAudience: 'Students',
    createdAt: '2026-03-10T11:00:00Z',
    priority: 'Normal',
  },
];

export const DEMO_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-001',
    schoolId: 'school-mwanza-modern-001',
    userId: 'user-mary-chacha',
    userName: 'Madam Mary Chacha',
    action: 'RELEASED_RESULTS',
    module: 'Examinations',
    recordId: 'exam-f4-premock-2026',
    details: 'Released Form IV Pre-NECTA Mock Examination 2026 results to student & parent portals following approval from Headmaster.',
    timestamp: '2026-03-02T14:30:00Z',
  },
  {
    id: 'aud-002',
    schoolId: 'school-mwanza-modern-001',
    userId: 'user-peter-mwita',
    userName: 'Mwl. Peter Mwita',
    action: 'APPROVED_RESULTS',
    module: 'Examinations',
    recordId: 'exam-f4-premock-2026',
    details: 'Verified mark integrity and gave executive sanction for Form IV Pre-Mock exam marks release.',
    timestamp: '2026-03-02T11:15:00Z',
  },
  {
    id: 'aud-003',
    schoolId: 'school-mwanza-modern-001',
    userId: 'user-john-magesa',
    userName: 'Mr. John Magesa',
    action: 'SUBMITTED_MARKS',
    module: 'Examinations',
    recordId: 'sub-phy',
    details: 'Submitted verified Physics marks for Form IV Alpha (35 candidates evaluated).',
    timestamp: '2026-03-01T16:20:00Z',
  },
  {
    id: 'aud-004',
    schoolId: 'school-mwanza-modern-001',
    userId: 'user-owner-001',
    userName: 'Dr. Aloyce M. Mtei',
    action: 'ASSIGNED_POSITION',
    module: 'Management Structure',
    recordId: 'user-grace-mushi',
    details: 'Assigned Discipline Mistress portfolio to Madam Grace Mushi.',
    timestamp: '2026-01-18T08:30:00Z',
  },
  {
    id: 'aud-005',
    schoolId: 'school-mwanza-modern-001',
    userId: 'user-baraka-kibona',
    userName: 'Mr. Baraka Kibona',
    action: 'RECORDED_PAYMENT',
    module: 'Finance',
    recordId: 'fee-1',
    details: 'Recorded TZS 1,500,000 tuition fee payment for Juma Bakari Mwinyi via NMB Bank transfer.',
    timestamp: '2026-01-14T10:45:00Z',
  },
];
