import { AppPermission, EducationLevel, GradingGradeRule, PositionTitle } from '../types';

export const TANZANIA_REGIONS = [
  'Arusha',
  'Dar es Salaam',
  'Dodoma',
  'Geita',
  'Iringa',
  'Kagera',
  'Katavi',
  'Kigoma',
  'Kilimanjaro',
  'Lindi',
  'Manyara',
  'Mara',
  'Mbeya',
  'Morogoro',
  'Mtwara',
  'Mwanza',
  'Njombe',
  'Pemba North',
  'Pemba South',
  'Pwani (Coast)',
  'Rukwa',
  'Ruvuma',
  'Shinyanga',
  'Simiyu',
  'Singida',
  'Songwe',
  'Tabora',
  'Tanga',
  'Unguja North',
  'Unguja South',
  'Urban West (Zanzibar)',
];

export const EDUCATION_LEVEL_OPTIONS: { level: EducationLevel; label: string; subtext: string; forms: string[] }[] = [
  {
    level: 'Primary',
    label: 'Primary Education (Elimu ya Msingi)',
    subtext: 'Standard 1 to Standard 7',
    forms: ['Standard 1', 'Standard 2', 'Standard 3', 'Standard 4', 'Standard 5', 'Standard 6', 'Standard 7'],
  },
  {
    level: 'O-Level',
    label: 'Ordinary Level Secondary (O-Level)',
    subtext: 'Form I to Form IV',
    forms: ['Form I', 'Form II', 'Form III', 'Form IV'],
  },
  {
    level: 'A-Level',
    label: 'Advanced Level Secondary (A-Level)',
    subtext: 'Form V to Form VI (Subject Combinations)',
    forms: ['Form V', 'Form VI'],
  },
];

export const DEFAULT_NECTA_GRADING_RULES: GradingGradeRule[] = [
  { grade: 'A', minScore: 75, maxScore: 100, point: 1, description: 'Bora Sana (Distinction)' },
  { grade: 'B', minScore: 65, maxScore: 74, point: 2, description: 'Vizuri Sana (Merit)' },
  { grade: 'C', minScore: 45, maxScore: 64, point: 3, description: 'Vizuri (Credit)' },
  { grade: 'D', minScore: 30, maxScore: 44, point: 4, description: 'Wastani (Pass)' },
  { grade: 'F', minScore: 0, maxScore: 29, point: 5, description: 'Feli (Fail)' },
];

export const DEFAULT_A_LEVEL_COMBINATIONS = [
  { code: 'PCM', name: 'Physics, Chemistry, Mathematics' },
  { code: 'PCB', name: 'Physics, Chemistry, Biology' },
  { code: 'PGM', name: 'Physics, Geography, Mathematics' },
  { code: 'CBG', name: 'Chemistry, Biology, Geography' },
  { code: 'CBA', name: 'Chemistry, Biology, Agriculture' },
  { code: 'EGM', name: 'Economics, Geography, Mathematics' },
  { code: 'HGL', name: 'History, Geography, Language (English)' },
  { code: 'HKL', name: 'History, Kiswahili, Language (English)' },
  { code: 'HGE', name: 'History, Geography, Economics' },
  { code: 'ECA', name: 'Economics, Commerce, Accountancy' },
  { code: 'CSE', name: 'Computer Science, Economics, Mathematics' },
];

export const POSITION_OPTIONS: { title: PositionTitle; swahili: string; description: string }[] = [
  { title: 'School Owner', swahili: 'Mmiliki wa Shule', description: 'Principal authority, overall school configuration & governance' },
  { title: 'Headmaster', swahili: 'Mkuu wa Shule', description: 'Executive head of administration, academic and institutional leadership' },
  { title: 'Headmistress', swahili: 'Mkuu wa Shule', description: 'Executive head of administration, academic and institutional leadership' },
  { title: 'Second Master', swahili: 'Makamu Mkuu wa Shule', description: 'Deputy administration, student affairs and discipline coordination' },
  { title: 'Second Mistress', swahili: 'Makamu Mkuu wa Shule', description: 'Deputy administration, student affairs and discipline coordination' },
  { title: 'Academic Master', swahili: 'Mkuu wa Taaluma', description: 'Academic director, examination scheduling, mark approvals & results release' },
  { title: 'Academic Mistress', swahili: 'Mkuu wa Taaluma', description: 'Academic director, examination scheduling, mark approvals & results release' },
  { title: 'Accountant', swahili: 'Mhasibu', description: 'School fees management, payments, receipts, income and expenditures' },
  { title: 'Discipline Master', swahili: 'Mlezi / Mkuu wa Nidhamu', description: 'Student conduct, behavioral records, suspensions and disciplinary warnings' },
  { title: 'Discipline Mistress', swahili: 'Mlezi / Mkuu wa Nidhamu', description: 'Student conduct, behavioral records, suspensions and disciplinary warnings' },
  { title: 'Head of Department', swahili: 'Mkuu wa Idara (HOD)', description: 'Department subject management, teacher allocation, performance oversight' },
  { title: 'Teacher', swahili: 'Mwalimu wa Somo', description: 'Subject instruction, daily attendance marking, and examination marks entry' },
  { title: 'Class Teacher', swahili: 'Mwalimu wa Darasa (Mkondo)', description: 'Stream focal point, class attendance monitoring, and pastoral care' },
  { title: 'Quality Assurance', swahili: 'Mdhibiti Ubora wa Shule', description: 'Curriculum delivery tracking, pedagogical evaluation & performance analytics' },
  { title: 'Parent', swahili: 'Mzazi / Mlezi', description: 'Guardian monitoring children results, attendance, fees, and school events' },
  { title: 'Student', swahili: 'Mwanafunzi', description: 'Enrolled learner accessing released results, timetable, and attendance records' },
];

export const DEFAULT_PERMISSIONS_BY_POSITION: Record<PositionTitle, AppPermission[]> = {
  'School Owner': [
    'students.view', 'students.create', 'students.edit', 'students.delete', 'students.move',
    'teachers.view', 'teachers.manage',
    'attendance.view',
    'marks.verify', 'marks.approve',
    'results.view', 'results.release', 'results.lock',
    'departments.manage', 'streams.manage', 'combinations.manage', 'subjects.manage',
    'finance.view', 'finance.manage',
    'discipline.view', 'discipline.manage',
    'qa.view', 'qa.manage',
    'reports.view', 'reports.export',
    'school.configure', 'audit.view',
  ],
  'Headmaster': [
    'students.view', 'students.create', 'students.edit', 'students.move',
    'teachers.view', 'teachers.manage',
    'attendance.view',
    'marks.verify', 'marks.approve',
    'results.view', 'results.release', 'results.lock',
    'departments.manage', 'streams.manage', 'combinations.manage', 'subjects.manage',
    'finance.view',
    'discipline.view', 'discipline.manage',
    'qa.view', 'qa.manage',
    'reports.view', 'reports.export',
    'audit.view',
  ],
  'Headmistress': [
    'students.view', 'students.create', 'students.edit', 'students.move',
    'teachers.view', 'teachers.manage',
    'attendance.view',
    'marks.verify', 'marks.approve',
    'results.view', 'results.release', 'results.lock',
    'departments.manage', 'streams.manage', 'combinations.manage', 'subjects.manage',
    'finance.view',
    'discipline.view', 'discipline.manage',
    'qa.view', 'qa.manage',
    'reports.view', 'reports.export',
    'audit.view',
  ],
  'Second Master': [
    'students.view', 'students.create', 'students.edit', 'students.move',
    'teachers.view',
    'attendance.view', 'attendance.mark',
    'results.view',
    'discipline.view', 'discipline.manage',
    'reports.view',
    'audit.view',
  ],
  'Second Mistress': [
    'students.view', 'students.create', 'students.edit', 'students.move',
    'teachers.view',
    'attendance.view', 'attendance.mark',
    'results.view',
    'discipline.view', 'discipline.manage',
    'reports.view',
    'audit.view',
  ],
  'Academic Master': [
    'students.view',
    'teachers.view',
    'attendance.view',
    'marks.enter', 'marks.submit', 'marks.verify', 'marks.approve',
    'results.view', 'results.release', 'results.lock',
    'departments.manage', 'streams.manage', 'combinations.manage', 'subjects.manage',
    'reports.view', 'reports.export',
    'qa.view',
  ],
  'Academic Mistress': [
    'students.view',
    'teachers.view',
    'attendance.view',
    'marks.enter', 'marks.submit', 'marks.verify', 'marks.approve',
    'results.view', 'results.release', 'results.lock',
    'departments.manage', 'streams.manage', 'combinations.manage', 'subjects.manage',
    'reports.view', 'reports.export',
    'qa.view',
  ],
  'Accountant': [
    'students.view',
    'finance.view', 'finance.manage',
    'reports.view', 'reports.export',
  ],
  'Discipline Master': [
    'students.view',
    'attendance.view',
    'discipline.view', 'discipline.manage',
    'reports.view',
  ],
  'Discipline Mistress': [
    'students.view',
    'attendance.view',
    'discipline.view', 'discipline.manage',
    'reports.view',
  ],
  'Head of Department': [
    'students.view',
    'teachers.view',
    'attendance.view',
    'marks.enter', 'marks.submit', 'marks.verify',
    'results.view',
    'subjects.manage',
    'reports.view',
  ],
  'Teacher': [
    'students.view',
    'attendance.view', 'attendance.mark',
    'marks.enter', 'marks.submit',
    'results.view',
  ],
  'Class Teacher': [
    'students.view', 'students.edit',
    'attendance.view', 'attendance.mark', 'attendance.edit',
    'marks.enter', 'marks.submit',
    'results.view',
    'reports.view',
  ],
  'Quality Assurance': [
    'students.view',
    'teachers.view',
    'attendance.view',
    'results.view',
    'qa.view', 'qa.manage',
    'reports.view', 'reports.export',
  ],
  'Parent': [
    'results.view',
    'attendance.view',
    'finance.view',
  ],
  'Student': [
    'results.view',
    'attendance.view',
  ],
};
